### ISSUE TITLE
addSharedLibrary crash

### ISSUE THREAD

**Issue by kings0527** [so-lli/VirtualXposed_12#6]
## 问题描述

release 安装包可以运行wechat，master错误

## 环境

机型：redmi
系统版本：android11
ROM版本：miui12 

## 补充

io.va.exposed64 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.va.exposed64:p0, PID: 21331
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object mirror.RefConstructor.newInstance(java.lang.Object[])' on a null object reference
        at com.lody.virtual.client.ipc.VPackageManager.libNameToSharedLibraryInfo(VPackageManager.java:214)
        at com.lody.virtual.client.ipc.VPackageManager.addSharedLibrary(VPackageManager.java:210)
        at com.lody.virtual.client.ipc.VPackageManager.addSharedLibraries(VPackageManager.java:192)
        at com.lody.virtual.client.ipc.VPackageManager.getApplicationInfo(VPackageManager.java:225)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:259)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:220)
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:215)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:166)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:163)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2195)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8087)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by imsourcandy** [comment]
Thanks for your feedback! I have added Android 12 support for WeChat so far. Adapting to Android 11 soon

**Comment by imsourcandy** [comment]
Fixed https://github.com/so-lli/VirtualXposed_12/commit/8f8b7fee6d30bfaa612aa43f0fa4576d66b19264, release version will be available in coming soon
